# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "workflows" branch
  push:
    branches: ["workflow"]
  pull_request:
    branches: ["workflow"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "image-checker"
  config-checker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install python package
        run: pip3 install dockloader

      - name: Pull docker image
        run: dockloader pull $(dockloader config | tail -n 1) --stdout --debug

      - name: List all docker images
        run: docker image ls
