# This is a basic workflow to help you get started with Actions

name: pr-check

# Controls when the workflow will run
on:
  # # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "image-checker"
  config-checker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install python package
        run: pip3 install dockloader

      - uses: actions/checkout@v4
        with:
          ref: "master"

      - name: Save old config files to temp
        run: cp -r cfgs/ /tmp/dockloader_cfgs

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Show diff
        run: |
          DIFF=$(python3 scripts/config-diff.py /tmp/dockloader_cfgs/docker.io cfgs/docker.io)
          echo "${DIFF}"
          if [ -z "${DIFF}" ]; then exit 2; fi

      - name: Pull docker image
        run: dockloader pull $(python3 scripts/config-diff.py /tmp/dockloader_cfgs/docker.io cfgs/docker.io) --stdout --debug

      - name: List all docker images
        run: docker image ls
